### ISSUE TITLE
Setting `Content-Type` to `multipart/form-data` returns error

### ISSUE THREAD

**Issue by YaManicKill** [DerEnderKeks/Yanius#31] opened 2017-08-30 11:33 UTC
Hi there,

When calling yanius with `Content-Type` set to `multipart/form-data`, I get this error:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Error: req.flash() requires sessions
            <br> &nbsp; &nbsp;at Error (native)
            <br> &nbsp; &nbsp;at IncomingMessage._flash [as flash] (/home/al/Yanius/node_modules/connect-flash/lib/flash.js:60:41)
            <br> &nbsp; &nbsp;at ServerResponse.res.render (/home/al/Yanius/node_modules/express-flash/lib/express-flash.js:28:35)
            <br> &nbsp; &nbsp;at /home/al/Yanius/app.js:218:9
            <br> &nbsp; &nbsp;at Layer.handle_error (/home/al/Yanius/node_modules/express/lib/router/layer.js:71:5)
            <br> &nbsp; &nbsp;at trim_prefix (/home/al/Yanius/node_modules/express/lib/router/index.js:315:13)
            <br> &nbsp; &nbsp;at /home/al/Yanius/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at next (/home/al/Yanius/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at trim_prefix (/home/al/Yanius/node_modules/express/lib/router/index.js:315:13)
            <br> &nbsp; &nbsp;at /home/al/Yanius/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at next (/home/al/Yanius/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at trim_prefix (/home/al/Yanius/node_modules/express/lib/router/index.js:315:13)
            <br> &nbsp; &nbsp;at /home/al/Yanius/node_modules/express/lib/router/index.js:284:7
            <br> &nbsp; &nbsp;at Immediate.next (/home/al/Yanius/node_modules/express/lib/router/index.js:275:10)
            <br> &nbsp; &nbsp;at tryOnImmediate (timers.js:645:5)
            <br> &nbsp; &nbsp;at processImmediate [as _immediateCallback] (timers.js:617:5)
        </pre>
    </body>
</html>
```

If I send the exact same request, but don't send a content-type, it successfully uploads. The problem with this is that I'm using a different tool to upload, and I can't edit it to send the request without the header.

**Comment by DerEnderKeks** [comment] 2017-08-30 12:13
I'll look into this as it's not the expected behavior and (normally) you are supposed to send the `Content-Type: multipart/form-data` header for file uploads. I never encountered this bug as I don't send any Content-Type header in my upload script or other applications I use to upload (even though I should..).

**Comment by ArsenArsen** [comment] 2017-08-30 16:20
`Content-Type: multipart/form-data; boundary=---------------------------00a2d2ad25dsd2ad2asdas3`

This is an example multipart header. `multipart` consists of boundaries which is why just `multipart/form-data` is invalid and will cause issues.
The software discovering this error is my own, and I constantly use multipart for my screenshots, which tells me there is something wrong with the configuration/server side.  
Just wanted to put this out there, also I am willing to help.

**Comment by YaManicKill** [comment] 2017-09-01 14:57
Oh yeah, so this gets a bit more confusing.

@ArsenArsen Is right, and that's why it's not working when I'm calling it from postman with a manual content header. When I disable the manual header, postman automatically inserts the header correctly "multipart/form-data; boundary=----WebKitFormBoundaryhFQ8OrBoznG1d9TL".

So the question is why isn't it working with KShare? That should be sending the boundary fine.

**Comment by DerEnderKeks** [comment] 2017-09-01 16:17
Yeah, I discovered that yesterday too when I analysed a Postman request with wireshark. As soon as ArsenArsen/KShare#36 gets resolved I can analyse the requests by KShare. Maybe I'll find the reason why it fails.

**Comment by ArsenArsen** [comment] 2017-09-01 19:47
![](https://i-am-going-back-to-school.please-kill.me/1839d7d.png) 

Works On My Machine:tm:

**Comment by DerEnderKeks** [comment] 2017-09-01 21:48
I'm gonna close this issue now as it's not a problem in this project but rather with [KShare](https://github.com/ArsenArsen/KShare).

Further discussion in ArsenArsen/KShare#36.

**Closed** 2017-09-01 21:52 UTC
Labels: invalid
